name: TorosamyElevator
main:  net.torosamy.torosamyElevator.TorosamyElevator
version: '${project.version}'
author: '${plugin.yml.author}'
website: '${plugin.yml.website}'
api-version: '${plugin.yml.api}'
depend:
  - TorosamyCore
softdepend:
  - Residence